# Generated by Django 2.2.7 on 2019-12-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_conferenceschedule_conference_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceschedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
