# Generated by Django 2.2.7 on 2019-12-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_conferenceschedule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceschedule',
            name='about',
            field=models.TextField(default='describe hehe'),
        ),
    ]
