# Generated by Django 2.2.7 on 2019-12-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191205_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='heading',
            new_name='types',
        ),
    ]
