# Generated by Django 2.2.7 on 2019-12-08 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191205_0759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogSingle',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
