# Generated by Django 2.2.7 on 2019-12-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20191208_0704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinForm',
            new_name='Join',
        ),
    ]
